spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/auth_dev?serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

